"""empty message

Revision ID: 23cce269e1bf
Revises: 3360b3bf9729
Create Date: 2021-02-19 00:43:47.121248

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '23cce269e1bf'
down_revision = '3360b3bf9729'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('order',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['user.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('product',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=80), nullable=False),
    sa.Column('price', sa.Integer(), nullable=False),
    sa.Column('photo_url', sa.String(length=80), nullable=False),
    sa.Column('qty', sa.Integer(), nullable=False),
    sa.Column('category', sa.String(length=80), nullable=False),
    sa.Column('order_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['order_id'], ['order.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('name'),
    sa.UniqueConstraint('photo_url')
    )
    op.add_column('user', sa.Column('adress', sa.String(length=80), nullable=False))
    op.add_column('user', sa.Column('city', sa.String(length=80), nullable=False))
    op.add_column('user', sa.Column('first_name', sa.String(length=80), nullable=False))
    op.add_column('user', sa.Column('last_name', sa.String(length=80), nullable=False))
    op.add_column('user', sa.Column('phone', sa.String(length=10), nullable=False))
    op.add_column('user', sa.Column('rewards_pts', sa.Integer(), nullable=False))
    op.add_column('user', sa.Column('state', sa.String(length=80), nullable=False))
    op.add_column('user', sa.Column('zip_code', sa.String(length=6), nullable=False))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('user', 'zip_code')
    op.drop_column('user', 'state')
    op.drop_column('user', 'rewards_pts')
    op.drop_column('user', 'phone')
    op.drop_column('user', 'last_name')
    op.drop_column('user', 'first_name')
    op.drop_column('user', 'city')
    op.drop_column('user', 'adress')
    op.drop_table('product')
    op.drop_table('order')
    # ### end Alembic commands ###
